### ISSUE TITLE
Unexpected Keyword Argument 'subsx'

### ISSUE THREAD

**Issue by njavro** [edersondisouza/linux-tsn-eval#1]
Hi, I have had success with running experiment and obtaining results folder. However, when I run analysis script:

`python3 run_analysis.py -d /path-to-results-folder/`

 the following error occurs:

> Traceback (most recent call last):
  File "/home/host2/TSN/linux-tsn-eval/sockets/analysis/run_analysis.py", line 228, in <module>
    main()
  File "/home/host2/TSN/linux-tsn-eval/sockets/analysis/run_analysis.py", line 189, in main
    PayloadFactor(metrics, hist_dir).histograms()
  File "/home/host2/TSN/linux-tsn-eval/sockets/analysis/factors.py", line 57, in histograms
    self.__histogram(metrics)
  File "/home/host2/TSN/linux-tsn-eval/sockets/analysis/factors.py", line 38, in __histogram
    hp.add_histogram(data_hist, edges, mean, stdev,
  File "/home/host2/TSN/linux-tsn-eval/sockets/analysis/plots.py", line 131, in add_histogram
    plot.set_xscale('log', subsx=[2, 4, 6, 8])
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/axes/_base.py", line 73, in wrapper
    return get_method(self)(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/axis.py", line 837, in _set_axes_scale
    ax._axis_map[name]._set_scale(value, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/axis.py", line 796, in _set_scale
    self._scale = mscale.scale_factory(value, self, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/matplotlib/scale.py", line 717, in scale_factory
    return scale_cls(axis, **kwargs)
TypeError: LogScale.__init__() got an unexpected keyword argument 'subsx'

Any detailed idea as to why the **subsx** argument fails to be passed? 

I still do get some sort of graphs and results, just not sure if those are fully correct and adequate.

**Comment by edersondisouza** [comment]
I guess matplotlib API has changed. You can either change the code to use the new API, as described at https://matplotlib.org/3.3.4/api/prev_api_changes/api_changes_3.3.0.html?highlight=subsx#log-symlog-scale-base-ticks-and-nonpos-specification, or pin matplotlib to version 2.2.

**Comment by njavro** [comment]
Thank you! It seemed to be version issue as you said.
